SELECT IAM.SISTEMA,
    CASE
        WHEN DWH.APPLICAZIONE IS NOT NULL THEN 'PRESENTE SU DWH'
        ELSE 'NON PRESENTE'
    END AS STATO
FROM [SVILUPPO].[IAM].[IA_Perimetro] AS IAM
LEFT JOIN [SVILUPPO].[DWH].[IA_NOSTD] AS DWH ON IAM.SISTEMA = DWH.APPLICAZIONE
ORDER BY IAM.SISTEMA