SELECT DWH.APPLICAZIONE,
    CASE
        WHEN IAM.SISTEMA IS NOT NULL THEN 'PRESENTE SU IAM'
        ELSE 'NON PRESENTE'
    END AS STATO
FROM [SVILUPPO].[DWH].[IA_STD] AS DWH
LEFT JOIN [SVILUPPO].[IAM].[IA_Perimetro] AS IAM ON DWH.APPLICAZIONE = IAM.SISTEMA
ORDER BY DWH.APPLICAZIONE