SELECT DWH.APPLICAZIONE,
    CASE
        WHEN IAM.SISTEMA IS NOT NULL THEN 'PRESENTE SU IAM'
        ELSE 'NON PRESENTE'
    END AS STATO
FROM [SVILUPPO].[DWH].[DB_NOSTD] AS DWH
LEFT JOIN [SVILUPPO].[IAM].[DB_Perimetro] AS IAM ON DWH.APPLICAZIONE = IAM.SISTEMA
ORDER BY DWH.APPLICAZIONE