SELECT
    DISTINCT APPLICAZIONE, COUNT(*)
    FROM IAM_DWH.ACCOUNTS_MONITORAGGIO
    WHERE LAYER='INTERFACCIA APPLICATIVA'
    AND TIPO_ACCOUNT IN ('SISTEMA','M2M')
GROUP BY APPLICAZIONE
ORDER BY APPLICAZIONE