SELECT DISTINCT APPLICAZIONE, COUNT (*)
FROM IAM_DWH.ACCOUNTS_MONITORAGGIO
WHERE 0=0
    AND LAYER='INTERFACCIA APPLICATIVA'
    AND TIPO_ACCOUNT IN ('STANDARD')
    AND APPLICAZIONE NOT IN ('HYDRA AAGG','PDLFREE','DEALERID','VTAM','GEMATRON')
GROUP BY APPLICAZIONE
ORDER BY APPLICAZIONE