SELECT
    DISTINCT APPLICAZIONE, COUNT(LOGIN) as NUMERO_UTENZE
    FROM IAM_DWH.ACCOUNTS_MONITORAGGIO
    WHERE LAYER='DATABASE'
    AND TIPO_ACCOUNT IN ('STANDARD','STANDARD OPS$')
GROUP BY APPLICAZIONE
ORDER BY APPLICAZIONE