SELECT
    DISTINCT APPLICAZIONE, COUNT(LOGIN)
    FROM IAM_DWH.ACCOUNTS_MONITORAGGIO
    WHERE LAYER='SISTEMA OPERATIVO'
    AND TIPO_ACCOUNT IN ('STANDARD')
GROUP BY APPLICAZIONE
ORDER BY APPLICAZIONE