SELECT
    DISTINCT APPLICAZIONE,COUNT(*)
    FROM IAM_DWH.ACCOUNTS_MONITORAGGIO
    WHERE LAYER IN ('SISTEMA OPERATIVO')
    AND TIPO_ACCOUNT IN ('SISTEMA','M2M')
GROUP BY APPLICAZIONE
ORDER BY APPLICAZIONE