SELECT
	SISTEMA,DESCRIZIONE_SISTEMA,ATTIVO,AMBIENTE,DATA_PRESA_IN_CARICO,GRUPPO_COMPETENTE,
	NOMINATIVO_OWNER,NOMINATIVO_RPR,CONSISTENZA,CONTROLLO_CONSISTENZA,PUBBLICA_CONSISTENZA,
	NIAM_EVOL,IAM_ENGINE,LAST_RUN,DATA_ULTIMO_EXPORT,NUMERO_EFFETTIVO_ACCOUNT,TOTALE_ACCOUNT,
	TOTALE_ACCOUNT_ATTIVI,TOTALE_ACCOUNT_ATTIVI_LAVORATI
FROM REPORT_SERVICE.dbo.APPL_SISTEMA_PERIMETRO
 WHERE SISTEMA NOT IN ('HYDRA AAGG','PDLFREE','DealerID','GEMATRON')
 	AND DATA_PRESA_IN_CARICO IS NOT NULL
	AND YEAR (DATA_PRESA_IN_CARICO) > '2000'
	AND ATTIVO='Si'
	AND AMBIENTE='ESERCIZIO'
ORDER BY SISTEMA
