SELECT
	SISTEMA,DESCRIZIONE_SISTEMA,ATTIVO,AMBIENTE,DATA_PRESA_IN_CARICO,GRUPPO_COMPETENTE,
	NOMINATIVO_GEST_APPLICATIVO,NOMINATIVO_RPR_GEST_APPL,NOMINATIVO_RPA,CONSISTENZA,
	CONTROLLO_CONSISTENZA,PUBBLICA_CONSISTENZA,NIAM_EVOL,IAM_ENGINE,DATA_ULTIMO_EXPORT,
	NUMERO_EFFETTIVO_ACCOUNT,TOTALE_ACCOUNT,TOTALE_ACCOUNT_ATTIVI,TOTALE_ACCOUNT_ATTIVI_LAVORATI
FROM REPORT_SERVICE.dbo.DB_SISTEMA_PERIMETRO
WHERE SISTEMA NOT LIKE '%_WL'
	AND DATA_PRESA_IN_CARICO IS NOT NULL
	AND YEAR (DATA_PRESA_IN_CARICO) > '2000'
	AND AMBIENTE='ESERCIZIO'
	AND ATTIVO='Si'
ORDER BY SISTEMA