SELECT distinct IAM.SISTEMA,
    CASE
        WHEN DWH.APPLICAZIONE IS NOT NULL THEN 'PRESENTE SU DWH'
        ELSE 'NON PRESENTE'
    END AS STATO
FROM [SVILUPPO].[IAM].[SO_Perimetro] AS IAM
LEFT JOIN [SVILUPPO].[DWH].[SO_STD] AS DWH ON IAM.SISTEMA = 'SO_'+DWH.APPLICAZIONE
ORDER BY IAM.SISTEMA