SELECT distinct DWH.APPLICAZIONE,
    CASE
        WHEN IAM.SISTEMA IS NOT NULL THEN 'PRESENTE SU IAM'
        ELSE 'NON PRESENTE'
    END AS STATO
FROM [SVILUPPO].[DWH].[SO_NOSTD] AS DWH
LEFT JOIN [SVILUPPO].[IAM].[SO_Perimetro] AS IAM ON 'SO_'+DWH.APPLICAZIONE = IAM.SISTEMA
ORDER BY DWH.APPLICAZIONE